HW-2
TuringClubMPEI/PythonCourse pull request #11
Opened 2023-04-15 16:37 UTC by Daniilmasloboinikov

2023-04-16 06:53 UTC, Pavel-Zhukoff requested changes

2023-04-16 06:53 UTC, Pavel-Zhukoff commented on ch02/Masloboynikov_Daniil/main.py
> +class Check(Bank):
Зачем наследование от банка?

2023-04-16 06:53 UTC, Pavel-Zhukoff commented on ch02/Masloboynikov_Daniil/main.py
> +    number = property(get_number, set_number)
лучше через декораторы делать

2023-04-16 06:53 UTC, Pavel-Zhukoff commented on ch02/Masloboynikov_Daniil/main.py
> +        self = bank.find_number(number)
вот так вообще лучше не делать, у тебя self это и так счет с номером number и прочими приколами

2023-04-16 06:53 UTC, Pavel-Zhukoff commented on ch02/Masloboynikov_Daniil/main.py
> +        self = bank.find_number(number)
То же самое (ниже тоже)

2023-04-16 06:53 UTC, Pavel-Zhukoff commented on ch02/Masloboynikov_Daniil/main.py
> +        self._amount = float(self.amount) - float(amount)
а если денег на счету не хватит, то мы в минус уйдем?

2023-04-16 06:53 UTC, Pavel-Zhukoff commented on ch02/Masloboynikov_Daniil/main.py
> +        print(self.amount)
лучше делать return, вообще не хорошо мешать вывод куда-либо и получение элемента. У тебя класс не должен знать как его будут отображать пользователю

2023-04-16 06:53 UTC, Pavel-Zhukoff commented on ch02/Masloboynikov_Daniil/main.py
> +        self.list_of_clients.append(Check)
переменные и аргументы функций надо называть с маленькой букв

2023-04-16 10:25 UTC, Daniilmasloboinikov commented on ch02/Masloboynikov_Daniil/main.py
> +class Check(Bank):
в начале думал, что понадобятся методы из класса счет, но в итоге сделал без них. После когда работал уже убрал

2023-04-16 10:38 UTC, Daniilmasloboinikov commented on ch02/Masloboynikov_Daniil/main.py
> +    number = property(get_number, set_number)
не могу понять, как это реализовать

2023-04-16 17:19 UTC, Pavel-Zhukoff requested changes

2023-04-16 17:19 UTC, Pavel-Zhukoff commented on ch02/Masloboynikov_Daniil/main.py
> +    number = property(get_number, set_number)
https://pythonpip.ru/osnovy/gettery-settery-python -хорошая статья там с примерами.

если коротко, тебе надо сделать 2, которые называются как аттрибут класса, например, number. Один принимает значение, т.е. имеет 2 аргумента(сетер), второй только возращает(гетер), и ты должен пометить их аннотациями `@property` - для гетера и `@<имя_метода>.setter` для сеттера, при этом важно чтобы у тебя совпадали названия обоих методов и имя метода в setter аннотации

2023-04-16 17:19 UTC, Pavel-Zhukoff commented on ch02/Masloboynikov_Daniil/main.py
> +class Check(Bank):
Ну тут убери тоже, а то это вводит в заблуждение

2023-04-21 13:38 UTC, Pavel-Zhukoff approved these changes

2023-04-25 06:37 UTC, merged